USE COMERCIO_OLTP
GO

DECLARE
			@ID_PRODUTO INT,
			@ID_NOTA_FISCAL INT,
			@QUANTIDADE INT,
			@VALOR NUMERIC(10,2),
			@TOTAL NUMERIC(10,2)


BEGIN
			SET @ID_PRODUTO = 
			(SELECT TOP 1 IDPRODUTO FROM PRODUTO ORDER BY NEWID())

			SET @ID_NOTA_FISCAL = 
			(SELECT TOP 1 IDNOTA FROM NOTA_FISCAL ORDER BY NEWID())

			SET @QUANTIDADE = 
			(SELECT ROUND(RAND()*4 + 1,0))

			SET @VALOR =
			(SELECT VALOR FROM PRODUTO WHERE IDPRODUTO = @ID_PRODUTO)

			SET @TOTAL = @QUANTIDADE * @VALOR

			INSERT INTO ITEM_NOTA(ID_PRODUTO,ID_NOTA_FISCAL,QUANTIDADE,TOTAL)
			VALUES
			(@ID_PRODUTO,@ID_NOTA_FISCAL,@QUANTIDADE,@TOTAL)

END
GO 27000
